spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatter?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      # 连接池配置
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  # Redis 配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: root
      
  # Nacos 配置
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启 SQL 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 实体类扫描路径
  type-aliases-package: com.indiegeeker.pojo.entity
  # Mapper XML 文件路径
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      # 主键生成策略
      id-type: auto
      # 逻辑删除字段
      logic-delete-field: deleted
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0

server:
  port: 18100
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: 2MB
    
logging:
  level:
    root: info
    # MyBatis SQL 日志
    com.indiegeeker.mapper: debug
