spring:
  application:
    name: auth-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev

# Chatter 文档配置
chatter:
  doc:
    enabled: true
    title: "认证服务 API 文档"
    version: "1.0.0"
    description: "Chatter 认证服务接口文档，提供用户注册、登录、权限管理等功能"
    contact:
      name: "IndieGeeker"
      email: "contact@indiegeeker.com"
      url: "https://indiegeeker.com"
    license:
      name: "Apache 2.0"
      url: "https://www.apache.org/licenses/LICENSE-2.0"
    server:
      url: "http://localhost:8080"
      description: "认证服务本地开发环境"
    group:
      name: "auth"
      base-package: "com.indiegeeker.auth.controller"
      description: "认证服务接口"

# Knife4j 配置
knife4j:
  enable: true
  setting:
    # 语言设置：中文
    language: zh_cn
    # 开启增强功能
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: "数据模型"
    enable-document-manage: true
    enable-host: false
    enable-host-text: ""
    enable-request-cache: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-after-script: true
    enable-response-code: true
    enable-dynamic-parameter: false
    enable-debug: true
    enable-footer: false
    enable-footer-custom: false

# SpringDoc 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: info
